default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ezmeetings_development

test:
  <<: *default
  database: ezmeetings_test
  
production:
  <<: *default
  database: ezmeetings_production
